FROM node:21-alpine3.19

WORKDIR /usr/src/app

# Copiar solo package.json
COPY package.json ./

# Instalar dependencias con legacy-peer-deps para evitar conflictos
RUN npm install --legacy-peer-deps

# Copiar el resto del código
COPY . .

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
