FROM node:21-alpine3.19
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
# Generar cliente de Prisma
RUN npx prisma generate
# Construir la aplicación NestJS
RUN npm run build
EXPOSE 3000
# Ejecutar migraciones y luego iniciar la aplicación
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:prod"]